server:
  error:
    include-message: always
  tomcat:
    relaxed-path-chars: "[,],|"
    relaxedQueryChars: '[,],|,{,},^,\,`,<,>'

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dpt_core
